version: "3.8"

services:

  # ---------------- POSTGRES ----------------
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: swiftpay
      POSTGRES_USER: swiftpay
      POSTGRES_PASSWORD: swiftpay
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - swiftpay-network

  # ---------------- ZOOKEEPER ----------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - swiftpay-network

  # ---------------- KAFKA ----------------
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - swiftpay-network

  # ---------------- TOPIC INIT ----------------
  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
      echo 'Waiting for Kafka...';
      sleep 20;

      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic payment-initiated --partitions 1 --replication-factor 1;
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic payment-completed --partitions 1 --replication-factor 1;
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic payment-failed --partitions 1 --replication-factor 1;

      echo 'Kafka topics created';
      "
    networks:
      - swiftpay-network

  # ---------------- REDIS ----------------
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - swiftpay-network

  # ---------------- TRANSACTION GATEWAY ----------------
  transaction-gateway:
    image: mallikrishna/transaction-gateway:latest
    container_name: transaction-gateway
    restart: always
    depends_on:
      - postgres
      - kafka
      - redis
      - ledger-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8080"
    networks:
      - swiftpay-network

  # ---------------- LEDGER SERVICE ----------------
  ledger-service:
    image: mallikrishna/ledger-service:latest
    container_name: ledger-service
    restart: always
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8080"
    networks:
      - swiftpay-network

  # ---------------- ANALYTICS WORKER ----------------
  analytics-worker:
    image: mallikrishna/analytics-worker:latest
    container_name: analytics-worker
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8080"
    networks:
      - swiftpay-network

# ---------------- NETWORK ----------------
networks:
  swiftpay-network:
    driver: bridge

# ---------------- VOLUMES ----------------
volumes:
  postgres-data:
  redis-data: