spring.application.name=analytics-worker

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/swiftpay
spring.datasource.username=swiftpay
spring.datasource.password=swiftpay
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092

################# actuator ##############################

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

# App info
info.app.name=ledger-service
info.app.version=1.0.0
info.app.description=Spring Boot Microservice