spring.application.name=ledger-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/swiftpay
spring.datasource.username=swiftpay
spring.datasource.password=swiftpay
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ng.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.bootstrap-servers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379

################# actuator ##############################

management.server.port=8082

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

# App info
info.app.name=ledger-service
info.app.version=1.0.0
info.app.description=Spring Boot Microservice